// ReSharper disable RedundantUsingDirective.Global
#pragma warning disable
global using System;
global using System.Buffers;
global using System.Collections;
global using System.Collections.Generic;
global using System.Collections.ObjectModel;
global using System.ComponentModel;
global using System.ComponentModel.DataAnnotations;
global using System.Data;
global using System.Data.Common;
global using System.Globalization;
global using System.IO;
global using System.Linq;
global using System.Net;
global using System.Net.Http;
global using System.Reactive.Disposables;
global using System.Reactive.Linq;
global using System.Reactive.Subjects;
global using System.Runtime;
global using System.Runtime.CompilerServices;
global using System.Text;
global using System.Threading;
global using System.Threading.Tasks;
global using System.Windows.Input;

global using Microsoft.Extensions.Logging;

global using Smart;
global using Smart.Avalonia.Messaging;
global using Smart.Avalonia.ViewModels;
global using Smart.Collections.Generic;
global using Smart.ComponentModel;
global using Smart.Mvvm;
global using Smart.Mvvm.Messaging;
global using Smart.Navigation;
global using Smart.Navigation.Attributes;
global using Smart.Navigation.Plugins.Parameter;
global using Smart.Navigation.Plugins.Scope;
global using Smart.Text;

//global using Template.DesktopApp;
//global using Template.DesktopApp.Domain;
//global using Template.DesktopApp.Messaging;
//global using Template.DesktopApp.Models;
//global using Template.DesktopApp.Models.Api;
//global using Template.DesktopApp.Models.Entity;
//global using Template.DesktopApp.Models.Input;
//global using Template.DesktopApp.State;
